version: "3.5"

volumes:
  nginx-shared:

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - nginx-shared:/nginx
    depends_on:
      - web

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  proxy:
    build:
      context: .
      dockerfile: docker/proxy/Dockerfile
    working_dir: /app
    ports:
      - "8083:8083"
    volumes:
      - .:/app
    command: docker/proxy/start.sh

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - proxy
    working_dir: /app
    ports:
      - "8888:8888"
    volumes:
      - nginx-shared:/nginx
      - .:/app
    command: docker/web/run_web.sh

  worker: &worker
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - proxy
    volumes:
      - .:/app
    command: docker/web/celery/worker/run.sh

  scheduler:
    <<: *worker
    command: docker/web/celery/scheduler/run.sh
